### ISSUE TITLE
feat request: command option to list all supported language

### ISSUE THREAD

**Issue by ShuguangSun** [Wilfred/difftastic#292]
Is it possible to list all supporte languages in command line?

For example, I find it support emacs lisp in the mannual. However, I don't know whether my version (from github release) supports emacs lisp or how to specify it in the command line (--language elisp not work).

**Comment by tizee** [comment]
`difftastic` uses extension to specify the language. You may use `difft --language el` to specify Emacs Lisp.
```
        --language <EXT>
            Override language detection. Inputs are assumed to have this file
            extension. When diffing directories, applies to all files.
```

I think this feature would make `difftastic` more user-friendly so instead of reading through the latest supported languages in [https://difftastic.wilfred.me.uk/languages_supported.html](https://difftastic.wilfred.me.uk/languages_supported.html), users could view current supported languages directly via `difftastic` in command line.

@Wilfred

**Comment by ShuguangSun** [comment]
Thanks.
