### ISSUE TITLE
Optional inline display (instead of side-by-side)

### ISSUE THREAD

**Issue by jplatte** [Wilfred/difftastic#34]
Would it be possible to provide an "inline" diff in addition to the current side-by-side diff? The highlighting differences compared to regular git diff are great, but for some reason I'm finding the side-by-side view to be hard to adjust to in the terminal (even though I regularily use it on GitHub and in VSCodium).

**Comment by Wilfred** [comment]
Yep, it's something I'm working on. Difftastic will respect `INLINE=y` today, but it's unfinished and buggy.

Inline display is difficult because difftastic ignores whitespace. In principle you could make a change and also reformat your file. In that case, there may be no lines after the current hunk that are equal!

It's definitely something difftastic needs though. Side-by-side display doesn't handle long lines very well.

**Comment by Xuanwo** [comment]
Seems we already support inline display? How about closing this issue?

**Comment by Wilfred** [comment]
Agreed :)
