### ISSUE TITLE
Textual diffing can be very slow

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/difftastic#86]
See e.g. magit.info-1 in https://github.com/Wilfred/.emacs.d/commit/0bb2a2812aba99cb5cac156cd21898611c48a99e

**Comment by martinvonz** [comment]
I very recently spent some time researching tree-diffing algorithms because my team wants to build a language-aware merge tool. That led me to papers like https://www.merlin.uzh.ch/contributionDocument/download/2162 and http://ilpubs.stanford.edu:8090/140/1/1996-15.pdf (I've still only skimmed part of them). I don't know how similar their ideas are to what you're currently doing. I just figured I'd point you to existing tree-diffing algorithms in case you hadn't considered it.

**Comment by Wilfred** [comment]
Hey @martinvonz! Getting totally nerd sniped here, but I have a few thoughts on merging too:

(1) Yep, the Chawathe paper gets cited a bunch in later papers. Do have a look at https://github.com/Wilfred/difftastic/wiki/Structural-Diffs if you haven't seen it, I've collected some tree-diffing references there.

The papers are not terribly accessible IME. I'd start with looking at Autochrome's explanation and maybe this part of the difftastic manual: https://difftastic.wilfred.me.uk/diffing.html, then the XML diffing blog post has a literature overview: http://useless-factor.blogspot.com/2008/01/matching-diffing-and-merging-xml.html

Papers tend to split into "fast but not a minimal diff" or "minimal diff but not as fast". Difftastic takes the latter approach today.

(2) Merging is a really messy problem in general, as I'm sure you're aware. You can have semantic merge conflicts that have no textual conflicts (e.g. two commits changing separate files), or textual conflicts with no semantic conflicts (git and hg both treat adjacent line changes as an conflict when they often aren't).

(3) Syntactic diffing is whitespace insensitive, but merging needs to make a decision on how to handle it. E.g.

```
// Original
var numbers = [10, 11, 12];

// They changed, causing a reflow.
var numbers = [
  10, 11,  100000000000000, 12
];

// I changed without causing a reflow.
var numbers = [9, 10, 11, 12];
```

It's not clear what to do here. I guess if you know what formatter the user has you could run that afterwards.

If you end up building something, I'd love to hear more about it :)

**Comment by martinvonz** [comment]
I'm glad I asked because that Structural-Diffs page was very useful. Thanks! :)

By the way, how slow is "very slow" here? How long does that diff of `magit.info-1` take?

Regarding merging, the "textual conflicts with no semantic conflicts" is most of what motivates us to spend time on the project -- it would be really nice to be able to merge changes that affect the same line.

In the case with whitespace changes, I had imagined we'd resolve it without caring about formatting. However, in your particular case, there's a newline and two spaces added before the "10" on one side and a single space added on the other side, so that might still be a conflict. If "10.5" had instead been added between the 10 and the 11, then it could be automatically resolved.

Languages like Python, where whitespace affects semantics, also makes merging harder. For example:

```
// Original
a = bar(1)

// They added an argument
a = bar(1,
  2)

// I moved the expression inside a block
if True:
  a = bar(1)

// Incorrect resolution
if True:
  a = bar(1,
  2)
```

If we assume that we detect that the expression is moved inside the block, then we still have to be careful to get the indentation right -- we can't simply use the indentation they used. I'm not sure how to solve that.

**Comment by Wilfred** [comment]
I'm fairly happy with text performance at this point, feel free to open issues if you have follow-up questions.
